stages:
    - build

build:
    stage: build
    variables:
      DOCKER_DRIVER: overlay2
      DOCKER_TLS_CERTDIR: ""
      DOCKER_HOST: tcp://localhost:2375/
    image: cr.yandex/yc/metadata-token-docker-helper:0.2
    services:
      - docker:19.03.1-dind
    script:
      - cd ./docker/app/crawler
      - docker build . -t cr.yandex/crpip7630dqdfpbk5ehs/crawler:app-$CI_COMMIT_SHORT_SHA
      - docker push cr.yandex/crpip7630dqdfpbk5ehs/crawler:app-$CI_COMMIT_SHORT_SHA
      - cd ../ui
      - docker build . -t cr.yandex/crpip7630dqdfpbk5ehs/crawler:ui-$CI_COMMIT_SHORT_SHA
      - docker push cr.yandex/crpip7630dqdfpbk5ehs/crawler:ui-$CI_COMMIT_SHORT_SHA