---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: crawler-ui
  labels:
    app: crawler
    component: ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crawler
      component: ui
  template:
    metadata:
      name: crawler-ui
      labels:
        app: crawler
        component: ui
    spec:
      containers:
      - image: cr.yandex/__REGISTRY__/ui:__VERSION__
        name: ui
        env:
        - name: MONGO
          value: mongodb
        - name: MONGO_PORT
          value: "27017"
        - name: FLASK_APP
          value: ui.py
